//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vertech.apiConsulta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.esocial.gov.br/ws", ConfigurationName="apiConsulta.EsocialService")]
    public interface EsocialService {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação consultaRequest não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vertech.apiConsulta.consultaResponse1 consultaRequest(Vertech.apiConsulta.consultaRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Vertech.apiConsulta.consultaResponse1> consultaRequestAsync(Vertech.apiConsulta.consultaRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class consultaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long grupoField;
        
        private bool grupoFieldSpecified;
        
        private long protocoloField;
        
        private bool protocoloFieldSpecified;
        
        private string iderpField;
        
        private string cdEventoField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long grupo {
            get {
                return this.grupoField;
            }
            set {
                this.grupoField = value;
                this.RaisePropertyChanged("grupo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grupoSpecified {
            get {
                return this.grupoFieldSpecified;
            }
            set {
                this.grupoFieldSpecified = value;
                this.RaisePropertyChanged("grupoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
                this.RaisePropertyChanged("protocolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool protocoloSpecified {
            get {
                return this.protocoloFieldSpecified;
            }
            set {
                this.protocoloFieldSpecified = value;
                this.RaisePropertyChanged("protocoloSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string iderp {
            get {
                return this.iderpField;
            }
            set {
                this.iderpField = value;
                this.RaisePropertyChanged("iderp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string cdEvento {
            get {
                return this.cdEventoField;
            }
            set {
                this.cdEventoField = value;
                this.RaisePropertyChanged("cdEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class consultaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private consultaProtocolo consultaProtocoloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public consultaProtocolo consultaProtocolo {
            get {
                return this.consultaProtocoloField;
            }
            set {
                this.consultaProtocoloField = value;
                this.RaisePropertyChanged("consultaProtocolo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class consultaProtocolo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private identificador identificadorField;
        
        private status statusField;
        
        private evento[] retornoEventosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public identificador identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
                this.RaisePropertyChanged("identificador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public status status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("evento", IsNullable=false)]
        public evento[] retornoEventos {
            get {
                return this.retornoEventosField;
            }
            set {
                this.retornoEventosField = value;
                this.RaisePropertyChanged("retornoEventos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class identificador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long loteField;
        
        private long protocoloField;
        
        private System.DateTime dtHrField;
        
        private string tpinscricaoField;
        
        private string nrinscricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
                this.RaisePropertyChanged("lote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
                this.RaisePropertyChanged("protocolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime dtHr {
            get {
                return this.dtHrField;
            }
            set {
                this.dtHrField = value;
                this.RaisePropertyChanged("dtHr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string tpinscricao {
            get {
                return this.tpinscricaoField;
            }
            set {
                this.tpinscricaoField = value;
                this.RaisePropertyChanged("tpinscricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string nrinscricao {
            get {
                return this.nrinscricaoField;
            }
            set {
                this.nrinscricaoField = value;
                this.RaisePropertyChanged("nrinscricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long cdRespostaField;
        
        private string descRespostaField;
        
        private string msgField;
        
        private ocorrencia[] ocorrenciasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long cdResposta {
            get {
                return this.cdRespostaField;
            }
            set {
                this.cdRespostaField = value;
                this.RaisePropertyChanged("cdResposta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descResposta {
            get {
                return this.descRespostaField;
            }
            set {
                this.descRespostaField = value;
                this.RaisePropertyChanged("descResposta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ocorrencia", IsNullable=false)]
        public ocorrencia[] ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
                this.RaisePropertyChanged("ocorrencias");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class ocorrencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long loteField;
        
        private bool loteFieldSpecified;
        
        private int seqField;
        
        private string dadosField;
        
        private long idIvesField;
        
        private long idIvesPaiField;
        
        private bool idIvesPaiFieldSpecified;
        
        private string mensagemField;
        
        private string regField;
        
        private string[] estruturaField;
        
        private string[] divergenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
                this.RaisePropertyChanged("lote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool loteSpecified {
            get {
                return this.loteFieldSpecified;
            }
            set {
                this.loteFieldSpecified = value;
                this.RaisePropertyChanged("loteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int seq {
            get {
                return this.seqField;
            }
            set {
                this.seqField = value;
                this.RaisePropertyChanged("seq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dados {
            get {
                return this.dadosField;
            }
            set {
                this.dadosField = value;
                this.RaisePropertyChanged("dados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long idIves {
            get {
                return this.idIvesField;
            }
            set {
                this.idIvesField = value;
                this.RaisePropertyChanged("idIves");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long idIvesPai {
            get {
                return this.idIvesPaiField;
            }
            set {
                this.idIvesPaiField = value;
                this.RaisePropertyChanged("idIvesPai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idIvesPaiSpecified {
            get {
                return this.idIvesPaiFieldSpecified;
            }
            set {
                this.idIvesPaiFieldSpecified = value;
                this.RaisePropertyChanged("idIvesPaiSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string reg {
            get {
                return this.regField;
            }
            set {
                this.regField = value;
                this.RaisePropertyChanged("reg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("msg", IsNullable=false)]
        public string[] estrutura {
            get {
                return this.estruturaField;
            }
            set {
                this.estruturaField = value;
                this.RaisePropertyChanged("estrutura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("msg", IsNullable=false)]
        public string[] divergencia {
            get {
                return this.divergenciaField;
            }
            set {
                this.divergenciaField = value;
                this.RaisePropertyChanged("divergencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class evento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cdEventoField;
        
        private long idErpField;
        
        private string nroProtocoloField;
        
        private string nroReciboField;
        
        private string situacaoField;
        
        private string loteIntegraField;
        
        private string nroProtocoloIntegraField;
        
        private string dtHrIntegraField;
        
        private string tpinscField;
        
        private string nrinscField;
        
        private string dtHrProtocoloField;
        
        private string dtHrReciboField;
        
        private erro[] errosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cdEvento {
            get {
                return this.cdEventoField;
            }
            set {
                this.cdEventoField = value;
                this.RaisePropertyChanged("cdEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long idErp {
            get {
                return this.idErpField;
            }
            set {
                this.idErpField = value;
                this.RaisePropertyChanged("idErp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nroProtocolo {
            get {
                return this.nroProtocoloField;
            }
            set {
                this.nroProtocoloField = value;
                this.RaisePropertyChanged("nroProtocolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string nroRecibo {
            get {
                return this.nroReciboField;
            }
            set {
                this.nroReciboField = value;
                this.RaisePropertyChanged("nroRecibo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string situacao {
            get {
                return this.situacaoField;
            }
            set {
                this.situacaoField = value;
                this.RaisePropertyChanged("situacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string loteIntegra {
            get {
                return this.loteIntegraField;
            }
            set {
                this.loteIntegraField = value;
                this.RaisePropertyChanged("loteIntegra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string nroProtocoloIntegra {
            get {
                return this.nroProtocoloIntegraField;
            }
            set {
                this.nroProtocoloIntegraField = value;
                this.RaisePropertyChanged("nroProtocoloIntegra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string dtHrIntegra {
            get {
                return this.dtHrIntegraField;
            }
            set {
                this.dtHrIntegraField = value;
                this.RaisePropertyChanged("dtHrIntegra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string tpinsc {
            get {
                return this.tpinscField;
            }
            set {
                this.tpinscField = value;
                this.RaisePropertyChanged("tpinsc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string nrinsc {
            get {
                return this.nrinscField;
            }
            set {
                this.nrinscField = value;
                this.RaisePropertyChanged("nrinsc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string dtHrProtocolo {
            get {
                return this.dtHrProtocoloField;
            }
            set {
                this.dtHrProtocoloField = value;
                this.RaisePropertyChanged("dtHrProtocolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string dtHrRecibo {
            get {
                return this.dtHrReciboField;
            }
            set {
                this.dtHrReciboField = value;
                this.RaisePropertyChanged("dtHrRecibo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("erro", IsNullable=false)]
        public erro[] erros {
            get {
                return this.errosField;
            }
            set {
                this.errosField = value;
                this.RaisePropertyChanged("erros");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class erro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cdErroField;
        
        private bool cdErroFieldSpecified;
        
        private string descErroField;
        
        private string tpErroField;
        
        private string localizacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int cdErro {
            get {
                return this.cdErroField;
            }
            set {
                this.cdErroField = value;
                this.RaisePropertyChanged("cdErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cdErroSpecified {
            get {
                return this.cdErroFieldSpecified;
            }
            set {
                this.cdErroFieldSpecified = value;
                this.RaisePropertyChanged("cdErroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descErro {
            get {
                return this.descErroField;
            }
            set {
                this.descErroField = value;
                this.RaisePropertyChanged("descErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string tpErro {
            get {
                return this.tpErroField;
            }
            set {
                this.tpErroField = value;
                this.RaisePropertyChanged("tpErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string localizacao {
            get {
                return this.localizacaoField;
            }
            set {
                this.localizacaoField = value;
                this.RaisePropertyChanged("localizacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esocial.gov.br/ws", Order=0)]
        public Vertech.apiConsulta.consultaRequest consultaRequest;
        
        public consultaRequest1() {
        }
        
        public consultaRequest1(Vertech.apiConsulta.consultaRequest consultaRequest) {
            this.consultaRequest = consultaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esocial.gov.br/ws", Order=0)]
        public Vertech.apiConsulta.consultaResponse consultaResponse;
        
        public consultaResponse1() {
        }
        
        public consultaResponse1(Vertech.apiConsulta.consultaResponse consultaResponse) {
            this.consultaResponse = consultaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EsocialServiceChannel : Vertech.apiConsulta.EsocialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EsocialServiceClient : System.ServiceModel.ClientBase<Vertech.apiConsulta.EsocialService>, Vertech.apiConsulta.EsocialService {
        
        public EsocialServiceClient() {
        }
        
        public EsocialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EsocialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EsocialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EsocialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vertech.apiConsulta.consultaResponse1 Vertech.apiConsulta.EsocialService.consultaRequest(Vertech.apiConsulta.consultaRequest1 request) {
            return base.Channel.consultaRequest(request);
        }
        
        public Vertech.apiConsulta.consultaResponse consultaRequest(Vertech.apiConsulta.consultaRequest consultaRequest1) {
            Vertech.apiConsulta.consultaRequest1 inValue = new Vertech.apiConsulta.consultaRequest1();
            inValue.consultaRequest = consultaRequest1;
            Vertech.apiConsulta.consultaResponse1 retVal = ((Vertech.apiConsulta.EsocialService)(this)).consultaRequest(inValue);
            return retVal.consultaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vertech.apiConsulta.consultaResponse1> Vertech.apiConsulta.EsocialService.consultaRequestAsync(Vertech.apiConsulta.consultaRequest1 request) {
            return base.Channel.consultaRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vertech.apiConsulta.consultaResponse1> consultaRequestAsync(Vertech.apiConsulta.consultaRequest consultaRequest) {
            Vertech.apiConsulta.consultaRequest1 inValue = new Vertech.apiConsulta.consultaRequest1();
            inValue.consultaRequest = consultaRequest;
            return ((Vertech.apiConsulta.EsocialService)(this)).consultaRequestAsync(inValue);
        }
    }
}
