apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: integradorIves
  annotations:
    github.com/project-slug: vertechit/integradorIves
spec:
  type: other
  lifecycle: unknown
  owner: guests
