//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorService.apiConsultaTXT {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.esocial.gov.br/ws", ConfigurationName="apiConsultaTXT.EsocialService")]
    public interface EsocialService {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação consultaRequest não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IntegradorService.apiConsultaTXT.consultaResponse1 consultaRequest(IntegradorService.apiConsultaTXT.consultaRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegradorService.apiConsultaTXT.consultaResponse1> consultaRequestAsync(IntegradorService.apiConsultaTXT.consultaRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class consultaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long grupoField;
        
        private bool grupoFieldSpecified;
        
        private long protocoloField;
        
        private bool protocoloFieldSpecified;
        
        private string iderpField;
        
        private string cdEventoField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long grupo {
            get {
                return this.grupoField;
            }
            set {
                this.grupoField = value;
                this.RaisePropertyChanged("grupo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grupoSpecified {
            get {
                return this.grupoFieldSpecified;
            }
            set {
                this.grupoFieldSpecified = value;
                this.RaisePropertyChanged("grupoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
                this.RaisePropertyChanged("protocolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool protocoloSpecified {
            get {
                return this.protocoloFieldSpecified;
            }
            set {
                this.protocoloFieldSpecified = value;
                this.RaisePropertyChanged("protocoloSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string iderp {
            get {
                return this.iderpField;
            }
            set {
                this.iderpField = value;
                this.RaisePropertyChanged("iderp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string cdEvento {
            get {
                return this.cdEventoField;
            }
            set {
                this.cdEventoField = value;
                this.RaisePropertyChanged("cdEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class consultaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private consultaResponseConsultaProtocolo consultaProtocoloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public consultaResponseConsultaProtocolo consultaProtocolo {
            get {
                return this.consultaProtocoloField;
            }
            set {
                this.consultaProtocoloField = value;
                this.RaisePropertyChanged("consultaProtocolo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class consultaResponseConsultaProtocolo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private consultaResponseConsultaProtocoloIdentificador identificadorField;
        
        private consultaResponseConsultaProtocoloStatus statusField;
        
        private consultaResponseConsultaProtocoloEvento[] retornoEventosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public consultaResponseConsultaProtocoloIdentificador identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
                this.RaisePropertyChanged("identificador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public consultaResponseConsultaProtocoloStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("evento", IsNullable=false)]
        public consultaResponseConsultaProtocoloEvento[] retornoEventos {
            get {
                return this.retornoEventosField;
            }
            set {
                this.retornoEventosField = value;
                this.RaisePropertyChanged("retornoEventos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class consultaResponseConsultaProtocoloIdentificador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int loteField;
        
        private int protocoloField;
        
        private System.DateTime dtHrField;
        
        private sbyte tpinscrField;
        
        private int nrinscrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
                this.RaisePropertyChanged("lote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
                this.RaisePropertyChanged("protocolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime dtHr {
            get {
                return this.dtHrField;
            }
            set {
                this.dtHrField = value;
                this.RaisePropertyChanged("dtHr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public sbyte tpinscr {
            get {
                return this.tpinscrField;
            }
            set {
                this.tpinscrField = value;
                this.RaisePropertyChanged("tpinscr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int nrinscr {
            get {
                return this.nrinscrField;
            }
            set {
                this.nrinscrField = value;
                this.RaisePropertyChanged("nrinscr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class consultaResponseConsultaProtocoloStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private sbyte cdRespostaField;
        
        private string descRespostaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public sbyte cdResposta {
            get {
                return this.cdRespostaField;
            }
            set {
                this.cdRespostaField = value;
                this.RaisePropertyChanged("cdResposta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descResposta {
            get {
                return this.descRespostaField;
            }
            set {
                this.descRespostaField = value;
                this.RaisePropertyChanged("descResposta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class consultaResponseConsultaProtocoloEvento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cdEventoField;
        
        private string idErpField;
        
        private string nroProtocoloField;
        
        private string nroReciboField;
        
        private string situacaoField;
        
        private string acaoField;
        
        private int idIvesField;
        
        private System.DateTime dtHrIntegraField;
        
        private System.DateTime dtHrProtocoloField;
        
        private bool dtHrProtocoloFieldSpecified;
        
        private System.DateTime dtHrReciboField;
        
        private bool dtHrReciboFieldSpecified;
        
        private string divergenteField;
        
        private consultaResponseConsultaProtocoloEventoOcorrencias ocorrenciasField;
        
        private consultaResponseConsultaProtocoloEventoErro[] errosField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cdEvento {
            get {
                return this.cdEventoField;
            }
            set {
                this.cdEventoField = value;
                this.RaisePropertyChanged("cdEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string idErp {
            get {
                return this.idErpField;
            }
            set {
                this.idErpField = value;
                this.RaisePropertyChanged("idErp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nroProtocolo {
            get {
                return this.nroProtocoloField;
            }
            set {
                this.nroProtocoloField = value;
                this.RaisePropertyChanged("nroProtocolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string nroRecibo {
            get {
                return this.nroReciboField;
            }
            set {
                this.nroReciboField = value;
                this.RaisePropertyChanged("nroRecibo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string situacao {
            get {
                return this.situacaoField;
            }
            set {
                this.situacaoField = value;
                this.RaisePropertyChanged("situacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string acao {
            get {
                return this.acaoField;
            }
            set {
                this.acaoField = value;
                this.RaisePropertyChanged("acao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int idIves {
            get {
                return this.idIvesField;
            }
            set {
                this.idIvesField = value;
                this.RaisePropertyChanged("idIves");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime dtHrIntegra {
            get {
                return this.dtHrIntegraField;
            }
            set {
                this.dtHrIntegraField = value;
                this.RaisePropertyChanged("dtHrIntegra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime dtHrProtocolo {
            get {
                return this.dtHrProtocoloField;
            }
            set {
                this.dtHrProtocoloField = value;
                this.RaisePropertyChanged("dtHrProtocolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtHrProtocoloSpecified {
            get {
                return this.dtHrProtocoloFieldSpecified;
            }
            set {
                this.dtHrProtocoloFieldSpecified = value;
                this.RaisePropertyChanged("dtHrProtocoloSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime dtHrRecibo {
            get {
                return this.dtHrReciboField;
            }
            set {
                this.dtHrReciboField = value;
                this.RaisePropertyChanged("dtHrRecibo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtHrReciboSpecified {
            get {
                return this.dtHrReciboFieldSpecified;
            }
            set {
                this.dtHrReciboFieldSpecified = value;
                this.RaisePropertyChanged("dtHrReciboSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string divergente {
            get {
                return this.divergenteField;
            }
            set {
                this.divergenteField = value;
                this.RaisePropertyChanged("divergente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public consultaResponseConsultaProtocoloEventoOcorrencias ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
                this.RaisePropertyChanged("ocorrencias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("erro", IsNullable=false)]
        public consultaResponseConsultaProtocoloEventoErro[] erros {
            get {
                return this.errosField;
            }
            set {
                this.errosField = value;
                this.RaisePropertyChanged("erros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class consultaResponseConsultaProtocoloEventoOcorrencias : object, System.ComponentModel.INotifyPropertyChanged {
        
        private consultaResponseConsultaProtocoloEventoOcorrenciasOcorrencia ocorrenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public consultaResponseConsultaProtocoloEventoOcorrenciasOcorrencia ocorrencia {
            get {
                return this.ocorrenciaField;
            }
            set {
                this.ocorrenciaField = value;
                this.RaisePropertyChanged("ocorrencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class consultaResponseConsultaProtocoloEventoOcorrenciasOcorrencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private consultaResponseConsultaProtocoloEventoOcorrenciasOcorrenciaEstrutura estruturaField;
        
        private string[] divergenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public consultaResponseConsultaProtocoloEventoOcorrenciasOcorrenciaEstrutura estrutura {
            get {
                return this.estruturaField;
            }
            set {
                this.estruturaField = value;
                this.RaisePropertyChanged("estrutura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("msg", IsNullable=false)]
        public string[] divergencia {
            get {
                return this.divergenciaField;
            }
            set {
                this.divergenciaField = value;
                this.RaisePropertyChanged("divergencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class consultaResponseConsultaProtocoloEventoOcorrenciasOcorrenciaEstrutura : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/ws")]
    public partial class consultaResponseConsultaProtocoloEventoErro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cdErroField;
        
        private string descErroField;
        
        private sbyte tpErroField;
        
        private string localizacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int cdErro {
            get {
                return this.cdErroField;
            }
            set {
                this.cdErroField = value;
                this.RaisePropertyChanged("cdErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descErro {
            get {
                return this.descErroField;
            }
            set {
                this.descErroField = value;
                this.RaisePropertyChanged("descErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public sbyte tpErro {
            get {
                return this.tpErroField;
            }
            set {
                this.tpErroField = value;
                this.RaisePropertyChanged("tpErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string localizacao {
            get {
                return this.localizacaoField;
            }
            set {
                this.localizacaoField = value;
                this.RaisePropertyChanged("localizacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esocial.gov.br/ws", Order=0)]
        public IntegradorService.apiConsultaTXT.consultaRequest consultaRequest;
        
        public consultaRequest1() {
        }
        
        public consultaRequest1(IntegradorService.apiConsultaTXT.consultaRequest consultaRequest) {
            this.consultaRequest = consultaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esocial.gov.br/ws", Order=0)]
        public IntegradorService.apiConsultaTXT.consultaResponse consultaResponse;
        
        public consultaResponse1() {
        }
        
        public consultaResponse1(IntegradorService.apiConsultaTXT.consultaResponse consultaResponse) {
            this.consultaResponse = consultaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EsocialServiceChannel : IntegradorService.apiConsultaTXT.EsocialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EsocialServiceClient : System.ServiceModel.ClientBase<IntegradorService.apiConsultaTXT.EsocialService>, IntegradorService.apiConsultaTXT.EsocialService {
        
        public EsocialServiceClient() {
        }
        
        public EsocialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EsocialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EsocialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EsocialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegradorService.apiConsultaTXT.consultaResponse1 IntegradorService.apiConsultaTXT.EsocialService.consultaRequest(IntegradorService.apiConsultaTXT.consultaRequest1 request) {
            return base.Channel.consultaRequest(request);
        }
        
        public IntegradorService.apiConsultaTXT.consultaResponse consultaRequest(IntegradorService.apiConsultaTXT.consultaRequest consultaRequest1) {
            IntegradorService.apiConsultaTXT.consultaRequest1 inValue = new IntegradorService.apiConsultaTXT.consultaRequest1();
            inValue.consultaRequest = consultaRequest1;
            IntegradorService.apiConsultaTXT.consultaResponse1 retVal = ((IntegradorService.apiConsultaTXT.EsocialService)(this)).consultaRequest(inValue);
            return retVal.consultaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegradorService.apiConsultaTXT.consultaResponse1> IntegradorService.apiConsultaTXT.EsocialService.consultaRequestAsync(IntegradorService.apiConsultaTXT.consultaRequest1 request) {
            return base.Channel.consultaRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegradorService.apiConsultaTXT.consultaResponse1> consultaRequestAsync(IntegradorService.apiConsultaTXT.consultaRequest consultaRequest) {
            IntegradorService.apiConsultaTXT.consultaRequest1 inValue = new IntegradorService.apiConsultaTXT.consultaRequest1();
            inValue.consultaRequest = consultaRequest;
            return ((IntegradorService.apiConsultaTXT.EsocialService)(this)).consultaRequestAsync(inValue);
        }
    }
}
